modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_matches_regexp:
        - "Could not connect to database"
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4" # defaults to "ip6"

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      body: "foo=bar&baz=quux"
      headers:
        Content-Type: application/x-www-form-urlencoded
      fail_if_not_matches_regexp:
        - "login successful"
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip6" # defaults to "ip6"

  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip6" # defaults to "ip6"

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4" # defaults to "ip4"

  dns:
    prober: dns
    timeout: 5s
    dns:
      query_name: "www.example.com"
      query_type: "A"
      preferred_ip_protocol: "ip4" # defaults to "ip4"

  ssh:
    prober: ssh
    timeout: 5s
    ssh:
      target_user: "user"
      password: "password"
      host_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvJ...Wj8klDNBq3"
      preferred_ip_protocol: "ip6" # defaults to "ip6"

  pop3s_banner:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: false
      query_response:
        - expect: "+OK"
          send: "EHLO example.com\r\n"
        - expect: "+OK"
          send: "STARTTLS\r\n"
        - expect: "+OK"
          tls: true
        - expect: "+OK"
          send: "QUIT\r\n"
      preferred_ip_protocol: "ip6" # defaults to "ip6"

  smtps_banner:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: false
      query_response:
        - expect: "220"
        - send: "EHLO example.com\r\n"
        - expect: "250"
        - send: "STARTTLS\r\n"
        - expect: "220"
          tls: true
        - send: "QUIT\r\n"
        - expect: "221"
      preferred_ip_protocol: "ip6" # defaults to "ip6"
